/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qNLSalKcLtD
 */
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";

export function BuyingOptions() {
  return (
    <div className="flex flex-col space-y-6  py-8 md:py-12 lg:py-24 ">
      <div className="border">
        <div className="bg-gray-200 p-4 text-center text-xl font-semibold">
          Buying Options
        </div>
        <form className="space-y-4 px-6 py-4">
          <RadioGroup defaultValue="singleUser">
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="singleuser" value="singleuser" />
              <Label htmlFor="singleuser">Single User $3999</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="multiuser" value="multiuser" />
              <Label htmlFor="multiuser">Multi User $7999</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="enterpriseuser" value="enterpriseuser" />
              <Label htmlFor="enterpriseuser">Enterprise User $9999</Label>
            </div>
          </RadioGroup>
          <Button className="bg-expertmarketinsight hover:bg-expertmarketinsight/90 text-white w-full">
            Buy Now
          </Button>
        </form>
      </div>
      <div className="grid grid-cols-[repeat(auto-fill,minmax(200px,1fr))] gap-4 px-6">
        <Button className="text-white uppercase">Request Sample</Button>
        <Button className="text-white uppercase">Request Discount</Button>
        <Button className="text-white uppercase">Pre Order Enquiry</Button>
        <Button className="text-white uppercase">Request Bulk Report</Button>
      </div>
    </div>
  );
}
